# Generated by Django 5.0 on 2023-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_room_icon_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=1, max_length=13),
            preserve_default=False,
        ),
    ]
