# Generated by Django 5.0 on 2023-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(blank=True),
        ),
    ]
